
version: '3.8'

# baseline setup does not expose any ports outside docker
# child configurations expose ports to docker/host/web as needed
services:

  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - volume_db:/var/lib/postgresql/data/
    networks:
      - backend

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - ELASTIC_USER=$ELASTIC_USER
      - discovery.type=$ELASTIC_DISCOVERY
    volumes:
      - volume_search:/usr/share/elasticsearch/data
    networks:
      - backend

  app:
    image: django.app.server.dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - SECRET_KEY=$SECRET_KEY
      - ALLOWED_HOSTS=$ALLOWED_HOSTS
      - DJANGO_PORT=$DJANGO_PORT
      - DJANGO_HOST=$DJANGO_HOST
      - DJANGO_DATA_DIR=$DJANGO_DATA_DIR
      - DJANGO_SUPERUSER_USER=$DJANGO_SUPERUSER_USER
      - DJANGO_SUPERUSER_EMAIL=$DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_PASSWORD=$DJANGO_SUPERUSER_PASSWORD

      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB

      - ELASTIC_HOST=$ELASTIC_HOST
      - ELASTIC_PORT=$ELASTIC_PORT
      - ELASTIC_USER=$ELASTIC_USER
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
    volumes:
      - volume_app:/var/lib/django/data/
    networks:
      - backend
    depends_on:
      - db
      - search

volumes:
  volume_db:
  volume_app:
  volume_search:

networks:
  backend:
    driver: bridge
