
# set baseline server image
FROM python:3.9.6-alpine

# set web group and permissions
RUN groupadd -r web && useradd -d /usr/src/srv -r -g web web \
    && chown web:web -R /usr/src/srv

# set server user and homedir
USER web
WORKDIR /usr/src/srv

# do not copy compiled files to image
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# copy project
COPY . .

# set shell as interactive entrypoint
CMD ["bash"]
