
version: '3.8'

services:
  # postgres service
  db:
    # production config - expose databse port only internally for app service
    expose:
      - $POSTGRES_PORT

  # django service
  app:
    image: django.app.server.app
    build:
      context: .
      dockerfile: Dockerfile.app
    command: pipenv run gunicorn config.wsgi:application --bind $DJANGO_HOST:$DJANGO_PORT
    volumes:
      - static:/usr/src/srv/02_movies_admin/static
    environment:
    # production config
      - DEBUG=False
      - CSRF_TRUSTED_ORIGINS=$CSRF_TRUSTED_ORIGINS
    # production config - expose application port only internally for web service
    expose:
      - $DJANGO_PORT

  # nginx service
  web:
    image: django.app.server.web
    build: 
      context: .
      dockerfile: Dockerfile.web
    # production config - map-through http to host
    volumes:
      - static:/var/www/static
    networks:
    - backend
    ports:
    - 80:80
    depends_on:
      - app

volumes:
  static: