# Generated by Django 3.2 on 2022-04-09 05:31

from django.db import migrations

def forwards_func(apps, schema_editor):
    # Этот код выполнится при применении миграции
    pass

def backwards_func(apps, schema_editor):
    # Этот код выполнится при отмене миграции
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_extensions'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE "content"."genre_film_work"
                ADD CONSTRAINT
                    "genre_film_work_film_work_id_genre_id_uniq"
                UNIQUE ("film_work_id", "genre_id");
            """,
            reverse_sql='ALTER TABLE "content"."genre_film_work" \
                DROP CONSTRAINT IF EXISTS \
                    genre_film_work_film_work_id_genre_id_uniq',
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE "content"."person_film_work"
                ADD CONSTRAINT
                    "person_film_work_film_work_id_person_id_role_uniq"
                UNIQUE ("film_work_id", "person_id", "role");
            """,
            reverse_sql='ALTER TABLE "content"."person_film_work" \
                DROP CONSTRAINT IF EXISTS \
                    person_film_work_film_work_id_person_id_role_uniq',
        )
    ]
