# Generated by Django 4.0.4 on 2022-04-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_timestamp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genrefilmwork',
            unique_together={('film_work', 'genre')},
        ),
        migrations.AlterUniqueTogether(
            name='personfilmwork',
            unique_together={('film_work', 'person', 'role')},
        ),
    ]
